### ISSUE TITLE
Dataset Latinoamerica

### ISSUE THREAD

**Issue by ZurMaD** [andrab/ecuacovid#1]
Estimado, antes que nada agradecerte por ofrecer los datos de la forma en la que la muestras.

Estamos usando su data para alimentar este [repositorio ](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica)en el cual recogemos datos de cada país de Latinoamérica.

Hemos encontrado datos anómalos al visualizar las gráficas:

![image](https://user-images.githubusercontent.com/28235457/82365555-697be600-99d6-11ea-9b7b-8419e86b62f5.png)

Quisiera saber si estos datos son los oficiales. Puedes ver la data[ ploteada aquí](https://datastudio.google.com/u/2/reporting/9b824956-4055-46da-8c40-0d46ded5ffba/page/QkcKB?params=%7B%22df10%22:%22include%25EE%2580%25800%25EE%2580%2580IN%25EE%2580%2580Ecuador%22%7D).

Muchas gracias.

**Comment by andrasio** [comment]
@ZurMaD Me parecen extraños esos gráficos. [Aquí está explicado cada uno de los archivos y sus campos](https://github.com/andrab/ecuacovid/blob/master/README.md). Están hasta el 16 de Mayo. 

No he actualizado los últimos tres días, todavía.

La información de aquí es exacta a los informes oficiales ([razón aquí](https://github.com/andrab/ecuacovid#por-qué-debo-confiar-en-la-precisión-de-estos-datos))

Aunque, noté algo extraño hace dos o tres días. La página (coronavirusecuador.com/data)(https://coronavirusecuador.com/data/) no proporciona datos abiertos (pero los informes que el gobierno publica los sacan de ahí). 

Lo curioso es que mirando al detalle esas visualizaciones los valores son distintos también. Por lo tanto empecé a compartir esos también y los [puedes ver aquí](https://github.com/andrab/ecuacovid/tree/master/datos_crudos/coronavirusecuador.com)

Graficando solo muertes (la métrica que uso) puedes observar las diferencias (comprar Ecuador vs Ecuador (coronavirusecuador.com) y "Ecuador y Probables" vs "Ecuador y Probables (coronavirusecuador.com) en la página [https://covid.andresrobalino.com](https://covid.andresrobalino.com/provincias)

Con la nueva información la curva no se ve tan distorsionada, eso explica que seguramente la que visualizan en esa página web la están actualizando y arreglando reportes atrasados de los informes diarios oficiales.

De todas maneras comparto ambos también.

**Comment by andrasio** [comment]
@ZurMaD Extraño. Antes entrando al enlace que me indicaste por alguna razón no salían hasta el 16 de Mayo. ¿Qué es lo extraño que estás observando?

**Comment by ZurMaD** [comment]
Mira esta columna

![image](https://user-images.githubusercontent.com/28235457/82377038-a7820580-99e8-11ea-84c6-1cb15f303a3e.png)

del archivo https://github.com/andrab/ecuacovid/blob/master/datos_crudos/positivas/por_fecha/provincias_por_dia.csv

**Comment by andrasio** [comment]
> Mira esta columna
> 
> ![image](https://user-images.githubusercontent.com/28235457/82377038-a7820580-99e8-11ea-84c6-1cb15f303a3e.png)
> 
> del archivo https://github.com/andrab/ecuacovid/blob/master/datos_crudos/positivas/por_fecha/provincias_por_dia.csv

@ZurMaD Tienes razón. Esa columna pertenece a las muertes del día 03/05. Hice al cambio correcto. Agregar pruebas a las provincias (Aprox. en Abril ~24 el gobierno no subió informe por dos o tres días y solo publicaron provincias y no los cantones) De manera que las positivas por provincia y cantons son mantenidos por separado hasta tomar una decisión.

Si encuentras otras cosas favor avisa.

Gracias de nuevo.
