### ISSUE TITLE
Total fallecidos 2020

### ISSUE THREAD

**Issue by Sebastian3387** [andrab/ecuacovid#10]
![image](https://user-images.githubusercontent.com/77119644/103926468-f6e78400-50e6-11eb-8ed9-389280351c88.png)

2020 se estarían contando datos de 2021. 
Fallecidos 2020: 113833
Fallecidos 2021: 188
Total: 114021
Saludos.

**Comment by andrasio** [comment]
@Sebastian3387 ¡Gracias! [Fixed](https://github.com/andrab/ecuacovid/commit/defb8a1d8e1a05e67fa44c19360454e1ebf9a1cc)
