### ISSUE TITLE
Fecha incorrecta en "vacunas.csv"

### ISSUE THREAD

**Issue by cacurio** [andrab/ecuacovid#11]
Los datos crudos del file "vacunas.csv", tiene la fecha incorrecta en el ultimo registro.
![Captura de Pantalla 2021-03-14 a la(s) 10 27 54](https://user-images.githubusercontent.com/36043948/111074329-78c1a800-84b0-11eb-8f2b-1264f3541d49.png)

**Comment by andrasio** [comment]
@cacurio Tageando @itos que anda en eso.

**Comment by itos** [comment]
@cacurio Gracias, ya está corrregido.

**Comment by andrasio** [comment]
@cacurio En 32dbaf815eac4f94f013be9dd5ee7cfd45ccf7d3 se hizo el cambio.
