### ISSUE TITLE
Población con al menos una dosis en el Vacunómetro del MSP

### ISSUE THREAD

**Issue by dapalaciosr** [andrab/ecuacovid#124]
Buenos días,

Un comentario sobre la información reportada por el Vacunómetro del MSP, que le escribí a Andrés Robalino hace unos días y me pidió que lo mencionara acá.

Antes de la introducción de la vacuna monodosis de CanSino, el número de personas en Ecuador con al menos una dosis era equivalente al número de primeras dosis aplicadas según lo reportado por el Vacunómetro. Debido a que el MSP cuenta cada dosis aplicada de CanSino solo como una segunda dosis, dicha equivalencia ya no existe. Ahora, el número de vacunados con al menos una dosis equivale al número de primeras dosis aplicadas más el número de dosis de CanSino aplicadas.

Esto podría tener implicaciones a la hora de pasar la información a Our World in Data u otros organismos.

Un saludo cordial

**Comment by itos** [comment]
@dapalaciosr Hola, por lo visto en Our World in Data usan las vacunas de monodosis como fully_vaccinated. Sin la distinción si es primera o segunda dosis. Our World in Data toma la sumatoria de personas parcialmente vacunadas y totalmente vacunadas como "at least one dose" po lo que no debería haber problema en el cálculo.
![Screenshot 2021-08-21 000626](https://user-images.githubusercontent.com/1735679/130311194-564a76c7-d063-47c5-a82d-1f89a0566f6f.png)

**Comment by andrasio** [comment]
Cerrando este issue, [quedó resuelto acá](https://github.com/owid/covid-19-data/pull/1976).

¡Muchas gracias! @dapalaciosr
