### ISSUE TITLE
VACUNAS: segunda_dosis del 10/04/2021

### ISSUE THREAD

**Issue by lucasrodes** [andrab/ecuacovid#26]
Buenas,
Ante todo muchas gracias por poner este recurso a disposición de la comunidad. Estamos usándolo en [owid/covid-19-data](https://github.com/owid/covid-19-data).

Recién nos dimos cuenta en [vuestros datos](https://github.com/andrab/ecuacovid/blob/master/datos_crudos/vacunas/vacunas.csv) que el campo `segunda_dosis` para el día 10/04/2021 parece que es más alto de lo que debería, puesto que a los días siguientes baja.

**Comment by andrasio** [comment]
@lucasrodes ¡Bienvenido Lucas!

Espero re-confirmación con @itos sobre tu indicación. Esta semana ha sido intensa respecto a [vacunaciones en nuestro país](https://twitter.com/paulmenam/status/1383090706810568708). Ese mismo día el ministerio de salud a través de twitter indicando que [están comprobadas y correctas](https://twitter.com/Salud_Ec/status/1383138713748799490?s=20) lo que publicaron.

Pero el día de hoy [señalando errores](https://www.salud.gob.ec/comunicado-oficial-error-de-datos-vacunacion-covid-19-en-tablero-estadistico/). 

@itos Mantiene día a día mirando la información. Espero confirmación sobre esto, y si hay, más detalles de @Panchurtado-gr 

Te mantendremos al tanto sobre qué hacer respecto a esto.

**Comment by andrasio** [comment]
@lucasrodes Por otro lado, hay otro archivo que están arribadas [por fabricantes](fabricantes.csv). Recuerdo que OWID también incluye esta información. ¿Tienes alguna necesidad de proporcionar los datos de alguna manera para que te sean de más utilidad en las automatizaciones de ustedes? (Campos, etcétera)

**Comment by itos** [comment]
> @lucasrodes ¡Bienvenido Lucas!
> 
> Espero re-confirmación con @itos sobre tu indicación. Esta semana ha sido intensa respecto a [vacunaciones en nuestro país](https://twitter.com/paulmenam/status/1383090706810568708). Ese mismo día el ministerio de salud a través de twitter indicando que [están comprobadas y correctas](https://twitter.com/Salud_Ec/status/1383138713748799490?s=20) lo que publicaron.
> 
> Pero el día de hoy [señalando errores](https://www.salud.gob.ec/comunicado-oficial-error-de-datos-vacunacion-covid-19-en-tablero-estadistico/).
> 
> @itos Mantiene día a día mirando la información. Espero confirmación sobre esto, y si hay, más detalles de @Panchurtado-gr
> 
> Te mantendremos al tanto sobre qué hacer respecto a esto.

Sí, es correcto. Fue debido a una corrección del MSP entre datos que según ellos [no estaban comprobados](https://twitter.com/Salud_Ec/status/1383138713748799490?s=20) y se ha reducido la cantidad de segunda dosis de ese día publicada.

**Comment by itos** [comment]
@andrasio debido a que el error del Ministerio de Salud Pública es confirmado y no era un dato correcto el que dieron se podría colocar la misma cifra de segunda_dosis 08/04/2021 en 10/04/2021.

**Comment by lucasrodes** [comment]
Buenas @andrasio @itos,
Gracias por vuestras rápidas respuestas y por ponerme en contexto. 

Entiendo pues que los datos del 10/04/2021 no acaban de ser del todo transparentes, pues?

Yo optaría por eliminar la entrada del 10/04/2021 hasta tener datos consistentes. Otra opción sería eliminar esas columnas con datos no consistentes (p.ej. dejar el campo de primeras dosis pero borrar los otros dos)

**Comment by itos** [comment]
@lucasrodes @andrasio Gracias por la recomendación. Procedí a eliminar la entrada del 10/04/2021. Ahora si hay datos diarios así que será más consistente las actualizaciones. Actualizado hasta 19/04/2021 en 34b9426d5f78cd9a0a745f4d495612368140d7eb

**Comment by lucasrodes** [comment]
Muchísimas gracias @andrasio @itos. Saludos
