### ISSUE TITLE
camas disponibles, utilizadas, disponibilidad UCIs.

### ISSUE THREAD

**Issue by rolotech75** [andrab/ecuacovid#9]
Hola!
Muchas gracias por los datos y por la información publicada, realmente me ha sido de mucha utilidad para desarrollar unos dashboards.
Podrías indicarnos en donde podria conseguir estos datos, o si los puedes generar de alguna fuente confiable:
- Cantidad de camas disponibles, cantidad de camas utilizadas en general, numero de camas utilizadas por pacientes COVID, por pais/provincia/cantón
- Cantidad de UCI disponibles, cantidad de UCIS utilizadas en general, número de UCIS utilizadas por pcaientes COVID, por país/provincia/cantón
- Datos por Género (pruebas, recuperados, positivos, etc.)

Gracias y saludos!
Rolando

**Comment by andrasio** [comment]
@rolotech75 Lamentablemente punto uno y punto dos no proporcionan (al menos no he encontrado). Si lo han indicado, imposible todo los días. Avísame si llegas a encontrar algo.

Datos por género proporcionaban en los informes, ya no lo hacen.
